### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by PAHeartBeat** [MrJoy/UnitySVG#2]
Hi Friends, I am trying to use this UnitySVG by Mr Joy, but unfrotunatly I got some file missing when I open project Unity 4.6.1. 
A scripti file shows missing on Plane object of test Scene

**Comment by PAHeartBeat** [comment]
Find the Missing files, missing flie is Invoke.cs I though is shoud show missing in inscpector becasue due to project update to Unity3D 4.6.1 from Unity 3.5.x

**Comment by MrJoy** [comment]
Sorry for the delay in responding!

Thank you for finding this!  I will try to update the project so people don't encounter this problem anymore.

**Comment by PAHeartBeat** [comment]
Hi Mr Joy,

That issue occurs in Unity 4.6x, so i think current project has been developed in older unity like Unity3D 3.x and I open it in Unity 4.x version so it's just may be projct upgradation. there not any tech issue with the projcet.

Thanks for your replay
