### ISSUE TITLE
Fix in Unity 5.5.0

### ISSUE THREAD

**Issue by LeandroFavero** [MrJoy/UnitySVG#3]
Hi,

To works in 5.5 version you must insert this line:
using UnityEngine.Profiling;

in

Implement.cs
SVGGArcAbs.cs
SVGGMoveTo.cs
SVGBasicDraw.cs
SVGGraphicsFill.cs
SVGGraphicsPath.cs
SVGGraphicsStroke.cs
SVGPathElement.cs

**Comment by MrJoy** [comment]
Thanks for the tip!

**Comment by MrJoy** [comment]
Whoops, forgot to note that this was fixed as of March 20.
