### ISSUE TITLE
The feColorMatrix Filter Primitive cant be parsed

### ISSUE THREAD

**Issue by BRINIS10** [MrJoy/UnitySVG#5]
Exception: Unknown element type 'feColorMatrix'!
SVGParser.Lookup (System.String name) (at Assets/svg/Assets/UnitySVG/Implementation/XMLParser/SVGParser.cs:140)
SVGParser.OnInlineElement (System.String name, System.Collections.Generic.Dictionary`2 attrs) (at Assets/svg/Assets/UnitySVG/Implementation/XMLParser/SVGParser.cs:78)
SmallXmlParser.ReadContent () (at Assets/svg/Assets/UnitySVG/Implementation/XMLParser/SmallXmlParser.cs:304)
SmallXmlParser.Parse (System.IO.TextReader input, IContentHandler handler) (at Assets/svg/Assets/UnitySVG/Implementation/XMLParser/SmallXmlParser.cs:225)
SVGParser..ctor (System.String text) (at Assets/svg/Assets/UnitySVG/Implementation/XMLParser/SVGParser.cs:57)
SVGDocument..ctor (System.String originalDocument, .SVGGraphics r) (at Assets/svg/Assets/UnitySVG/Implementation/SVG/DOM/DocumentStructure/SVGDocument.cs:18)
Implement.CreateEmptySVGDocument () (at Assets/svg/Assets/UnitySVG/Implement.cs:15)

**Comment by MrJoy** [comment]
Could you provide a sample SVG that reproduces the issue?

**Comment by MrJoy** [comment]
Ah, NM.

Yep.  That element is, unfortunately, not supported -- and I really don't have the expertise to add support.  Apologies!

Honestly though, at this point, a better option might be to make a parameterized Substance material that takes an SVG file as a parameter, and simply renders it.  Yeah, you'd need to pick up a copy of Substance Designer, but the results should be vastly better performing and compatibility vastly better:

https://support.allegorithmic.com/documentation/display/SD5/SVG+node
