### ISSUE TITLE
The name `Profiler' does not exist in the current context

### ISSUE THREAD

**Issue by LuannLuna** [MrJoy/UnitySVG#6]
Hi, i'm try to test your project. But when I downloaded the project and try to execute, I had this error: "The name `Profiler' does not exist in the current context". Can you help me? It's seem that is missing some file.

**Comment by MrJoy** [comment]
Sounds like Unity did some re-arranging of their namespaces.  A quick search suggest you may have some luck by adding `using UnityEngine.Profiling;` at the top of relevant files -- until I can get around to updating things.

**Comment by MrJoy** [comment]
Fixed on latest master.
